ALTER TABLE "User" ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Public Read User" ON "User";
DROP POLICY IF EXISTS "Deny All Select User" ON "User";
DROP POLICY IF EXISTS "Deny All Insert User" ON "User";
DROP POLICY IF EXISTS "Deny All Update User" ON "User";
DROP POLICY IF EXISTS "Deny All Delete User" ON "User";
CREATE POLICY "Deny All Select User" ON "User" FOR SELECT TO PUBLIC USING (false);
CREATE POLICY "Deny All Insert User" ON "User" FOR INSERT TO PUBLIC WITH CHECK (false);
CREATE POLICY "Deny All Update User" ON "User" FOR UPDATE TO PUBLIC USING (false);
CREATE POLICY "Deny All Delete User" ON "User" FOR DELETE TO PUBLIC USING (false);

ALTER TABLE "VerificationToken" ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Public Read VerificationToken" ON "VerificationToken";
DROP POLICY IF EXISTS "Deny All Select VerificationToken" ON "VerificationToken";
DROP POLICY IF EXISTS "Deny All Insert VerificationToken" ON "VerificationToken";
DROP POLICY IF EXISTS "Deny All Update VerificationToken" ON "VerificationToken";
DROP POLICY IF EXISTS "Deny All Delete VerificationToken" ON "VerificationToken";
CREATE POLICY "Deny All Select VerificationToken" ON "VerificationToken" FOR SELECT TO PUBLIC USING (false);
CREATE POLICY "Deny All Insert VerificationToken" ON "VerificationToken" FOR INSERT TO PUBLIC WITH CHECK (false);
CREATE POLICY "Deny All Update VerificationToken" ON "VerificationToken" FOR UPDATE TO PUBLIC USING (false);
CREATE POLICY "Deny All Delete VerificationToken" ON "VerificationToken" FOR DELETE TO PUBLIC USING (false);

ALTER TABLE "PasswordResetToken" ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Public Read PasswordResetToken" ON "PasswordResetToken";
DROP POLICY IF EXISTS "Deny All Select PasswordResetToken" ON "PasswordResetToken";
DROP POLICY IF EXISTS "Deny All Insert PasswordResetToken" ON "PasswordResetToken";
DROP POLICY IF EXISTS "Deny All Update PasswordResetToken" ON "PasswordResetToken";
DROP POLICY IF EXISTS "Deny All Delete PasswordResetToken" ON "PasswordResetToken";
CREATE POLICY "Deny All Select PasswordResetToken" ON "PasswordResetToken" FOR SELECT TO PUBLIC USING (false);
CREATE POLICY "Deny All Insert PasswordResetToken" ON "PasswordResetToken" FOR INSERT TO PUBLIC WITH CHECK (false);
CREATE POLICY "Deny All Update PasswordResetToken" ON "PasswordResetToken" FOR UPDATE TO PUBLIC USING (false);
CREATE POLICY "Deny All Delete PasswordResetToken" ON "PasswordResetToken" FOR DELETE TO PUBLIC USING (false);

ALTER TABLE "BusinessProfile" ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Public Read BusinessProfile" ON "BusinessProfile";
DROP POLICY IF EXISTS "Deny All Select BusinessProfile" ON "BusinessProfile";
DROP POLICY IF EXISTS "Deny All Insert BusinessProfile" ON "BusinessProfile";
DROP POLICY IF EXISTS "Deny All Update BusinessProfile" ON "BusinessProfile";
DROP POLICY IF EXISTS "Deny All Delete BusinessProfile" ON "BusinessProfile";
CREATE POLICY "Deny All Select BusinessProfile" ON "BusinessProfile" FOR SELECT TO PUBLIC USING (false);
CREATE POLICY "Deny All Insert BusinessProfile" ON "BusinessProfile" FOR INSERT TO PUBLIC WITH CHECK (false);
CREATE POLICY "Deny All Update BusinessProfile" ON "BusinessProfile" FOR UPDATE TO PUBLIC USING (false);
CREATE POLICY "Deny All Delete BusinessProfile" ON "BusinessProfile" FOR DELETE TO PUBLIC USING (false);

ALTER TABLE "PaymentCustomer" ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Public Read PaymentCustomer" ON "PaymentCustomer";
DROP POLICY IF EXISTS "Deny All Select PaymentCustomer" ON "PaymentCustomer";
DROP POLICY IF EXISTS "Deny All Insert PaymentCustomer" ON "PaymentCustomer";
DROP POLICY IF EXISTS "Deny All Update PaymentCustomer" ON "PaymentCustomer";
DROP POLICY IF EXISTS "Deny All Delete PaymentCustomer" ON "PaymentCustomer";
CREATE POLICY "Deny All Select PaymentCustomer" ON "PaymentCustomer" FOR SELECT TO PUBLIC USING (false);
CREATE POLICY "Deny All Insert PaymentCustomer" ON "PaymentCustomer" FOR INSERT TO PUBLIC WITH CHECK (false);
CREATE POLICY "Deny All Update PaymentCustomer" ON "PaymentCustomer" FOR UPDATE TO PUBLIC USING (false);
CREATE POLICY "Deny All Delete PaymentCustomer" ON "PaymentCustomer" FOR DELETE TO PUBLIC USING (false);

ALTER TABLE "SubscriptionPlan" ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Public Read SubscriptionPlan" ON "SubscriptionPlan";
DROP POLICY IF EXISTS "Deny All Select SubscriptionPlan" ON "SubscriptionPlan";
DROP POLICY IF EXISTS "Deny All Insert SubscriptionPlan" ON "SubscriptionPlan";
DROP POLICY IF EXISTS "Deny All Update SubscriptionPlan" ON "SubscriptionPlan";
DROP POLICY IF EXISTS "Deny All Delete SubscriptionPlan" ON "SubscriptionPlan";
CREATE POLICY "Public Read SubscriptionPlan" ON "SubscriptionPlan" FOR SELECT TO PUBLIC USING (true);
CREATE POLICY "Deny All Insert SubscriptionPlan" ON "SubscriptionPlan" FOR INSERT TO PUBLIC WITH CHECK (false);
CREATE POLICY "Deny All Update SubscriptionPlan" ON "SubscriptionPlan" FOR UPDATE TO PUBLIC USING (false);
CREATE POLICY "Deny All Delete SubscriptionPlan" ON "SubscriptionPlan" FOR DELETE TO PUBLIC USING (false);

ALTER TABLE "Subscription" ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Public Read Subscription" ON "Subscription";
DROP POLICY IF EXISTS "Deny All Select Subscription" ON "Subscription";
DROP POLICY IF EXISTS "Deny All Insert Subscription" ON "Subscription";
DROP POLICY IF EXISTS "Deny All Update Subscription" ON "Subscription";
DROP POLICY IF EXISTS "Deny All Delete Subscription" ON "Subscription";
CREATE POLICY "Deny All Select Subscription" ON "Subscription" FOR SELECT TO PUBLIC USING (false);
CREATE POLICY "Deny All Insert Subscription" ON "Subscription" FOR INSERT TO PUBLIC WITH CHECK (false);
CREATE POLICY "Deny All Update Subscription" ON "Subscription" FOR UPDATE TO PUBLIC USING (false);
CREATE POLICY "Deny All Delete Subscription" ON "Subscription" FOR DELETE TO PUBLIC USING (false);

ALTER TABLE "PaymentTransaction" ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Public Read PaymentTransaction" ON "PaymentTransaction";
DROP POLICY IF EXISTS "Deny All Select PaymentTransaction" ON "PaymentTransaction";
DROP POLICY IF EXISTS "Deny All Insert PaymentTransaction" ON "PaymentTransaction";
DROP POLICY IF EXISTS "Deny All Update PaymentTransaction" ON "PaymentTransaction";
DROP POLICY IF EXISTS "Deny All Delete PaymentTransaction" ON "PaymentTransaction";
CREATE POLICY "Deny All Select PaymentTransaction" ON "PaymentTransaction" FOR SELECT TO PUBLIC USING (false);
CREATE POLICY "Deny All Insert PaymentTransaction" ON "PaymentTransaction" FOR INSERT TO PUBLIC WITH CHECK (false);
CREATE POLICY "Deny All Update PaymentTransaction" ON "PaymentTransaction" FOR UPDATE TO PUBLIC USING (false);
CREATE POLICY "Deny All Delete PaymentTransaction" ON "PaymentTransaction" FOR DELETE TO PUBLIC USING (false);

ALTER TABLE "EmailLog" ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Public Read EmailLog" ON "EmailLog";
DROP POLICY IF EXISTS "Deny All Select EmailLog" ON "EmailLog";
DROP POLICY IF EXISTS "Deny All Insert EmailLog" ON "EmailLog";
DROP POLICY IF EXISTS "Deny All Update EmailLog" ON "EmailLog";
DROP POLICY IF EXISTS "Deny All Delete EmailLog" ON "EmailLog";
CREATE POLICY "Deny All Select EmailLog" ON "EmailLog" FOR SELECT TO PUBLIC USING (false);
CREATE POLICY "Deny All Insert EmailLog" ON "EmailLog" FOR INSERT TO PUBLIC WITH CHECK (false);
CREATE POLICY "Deny All Update EmailLog" ON "EmailLog" FOR UPDATE TO PUBLIC USING (false);
CREATE POLICY "Deny All Delete EmailLog" ON "EmailLog" FOR DELETE TO PUBLIC USING (false);

ALTER TABLE "NotificationLog" ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Public Read NotificationLog" ON "NotificationLog";
DROP POLICY IF EXISTS "Deny All Select NotificationLog" ON "NotificationLog";
DROP POLICY IF EXISTS "Deny All Insert NotificationLog" ON "NotificationLog";
DROP POLICY IF EXISTS "Deny All Update NotificationLog" ON "NotificationLog";
DROP POLICY IF EXISTS "Deny All Delete NotificationLog" ON "NotificationLog";
CREATE POLICY "Deny All Select NotificationLog" ON "NotificationLog" FOR SELECT TO PUBLIC USING (false);
CREATE POLICY "Deny All Insert NotificationLog" ON "NotificationLog" FOR INSERT TO PUBLIC WITH CHECK (false);
CREATE POLICY "Deny All Update NotificationLog" ON "NotificationLog" FOR UPDATE TO PUBLIC USING (false);
CREATE POLICY "Deny All Delete NotificationLog" ON "NotificationLog" FOR DELETE TO PUBLIC USING (false);

ALTER TABLE "AdminActionLog" ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Public Read AdminActionLog" ON "AdminActionLog";
DROP POLICY IF EXISTS "Deny All Select AdminActionLog" ON "AdminActionLog";
DROP POLICY IF EXISTS "Deny All Insert AdminActionLog" ON "AdminActionLog";
DROP POLICY IF EXISTS "Deny All Update AdminActionLog" ON "AdminActionLog";
DROP POLICY IF EXISTS "Deny All Delete AdminActionLog" ON "AdminActionLog";
CREATE POLICY "Deny All Select AdminActionLog" ON "AdminActionLog" FOR SELECT TO PUBLIC USING (false);
CREATE POLICY "Deny All Insert AdminActionLog" ON "AdminActionLog" FOR INSERT TO PUBLIC WITH CHECK (false);
CREATE POLICY "Deny All Update AdminActionLog" ON "AdminActionLog" FOR UPDATE TO PUBLIC USING (false);
CREATE POLICY "Deny All Delete AdminActionLog" ON "AdminActionLog" FOR DELETE TO PUBLIC USING (false);

ALTER TABLE "StayListing" ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Public Read StayListing" ON "StayListing";
DROP POLICY IF EXISTS "Deny All Select StayListing" ON "StayListing";
DROP POLICY IF EXISTS "Deny All Insert StayListing" ON "StayListing";
DROP POLICY IF EXISTS "Deny All Update StayListing" ON "StayListing";
DROP POLICY IF EXISTS "Deny All Delete StayListing" ON "StayListing";
CREATE POLICY "Public Read StayListing" ON "StayListing" FOR SELECT TO PUBLIC USING (true);
CREATE POLICY "Deny All Insert StayListing" ON "StayListing" FOR INSERT TO PUBLIC WITH CHECK (false);
CREATE POLICY "Deny All Update StayListing" ON "StayListing" FOR UPDATE TO PUBLIC USING (false);
CREATE POLICY "Deny All Delete StayListing" ON "StayListing" FOR DELETE TO PUBLIC USING (false);

ALTER TABLE "StayListingImage" ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Public Read StayListingImage" ON "StayListingImage";
DROP POLICY IF EXISTS "Deny All Select StayListingImage" ON "StayListingImage";
DROP POLICY IF EXISTS "Deny All Insert StayListingImage" ON "StayListingImage";
DROP POLICY IF EXISTS "Deny All Update StayListingImage" ON "StayListingImage";
DROP POLICY IF EXISTS "Deny All Delete StayListingImage" ON "StayListingImage";
CREATE POLICY "Public Read StayListingImage" ON "StayListingImage" FOR SELECT TO PUBLIC USING (true);
CREATE POLICY "Deny All Insert StayListingImage" ON "StayListingImage" FOR INSERT TO PUBLIC WITH CHECK (false);
CREATE POLICY "Deny All Update StayListingImage" ON "StayListingImage" FOR UPDATE TO PUBLIC USING (false);
CREATE POLICY "Deny All Delete StayListingImage" ON "StayListingImage" FOR DELETE TO PUBLIC USING (false);

ALTER TABLE "ListingSubmissionHistory" ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Public Read ListingSubmissionHistory" ON "ListingSubmissionHistory";
DROP POLICY IF EXISTS "Deny All Select ListingSubmissionHistory" ON "ListingSubmissionHistory";
DROP POLICY IF EXISTS "Deny All Insert ListingSubmissionHistory" ON "ListingSubmissionHistory";
DROP POLICY IF EXISTS "Deny All Update ListingSubmissionHistory" ON "ListingSubmissionHistory";
DROP POLICY IF EXISTS "Deny All Delete ListingSubmissionHistory" ON "ListingSubmissionHistory";
CREATE POLICY "Deny All Select ListingSubmissionHistory" ON "ListingSubmissionHistory" FOR SELECT TO PUBLIC USING (false);
CREATE POLICY "Deny All Insert ListingSubmissionHistory" ON "ListingSubmissionHistory" FOR INSERT TO PUBLIC WITH CHECK (false);
CREATE POLICY "Deny All Update ListingSubmissionHistory" ON "ListingSubmissionHistory" FOR UPDATE TO PUBLIC USING (false);
CREATE POLICY "Deny All Delete ListingSubmissionHistory" ON "ListingSubmissionHistory" FOR DELETE TO PUBLIC USING (false);

ALTER TABLE "Place" ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Public Read Place" ON "Place";
DROP POLICY IF EXISTS "Deny All Select Place" ON "Place";
DROP POLICY IF EXISTS "Deny All Insert Place" ON "Place";
DROP POLICY IF EXISTS "Deny All Update Place" ON "Place";
DROP POLICY IF EXISTS "Deny All Delete Place" ON "Place";
CREATE POLICY "Public Read Place" ON "Place" FOR SELECT TO PUBLIC USING (true);
CREATE POLICY "Deny All Insert Place" ON "Place" FOR INSERT TO PUBLIC WITH CHECK (false);
CREATE POLICY "Deny All Update Place" ON "Place" FOR UPDATE TO PUBLIC USING (false);
CREATE POLICY "Deny All Delete Place" ON "Place" FOR DELETE TO PUBLIC USING (false);

ALTER TABLE "PlaceSource" ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Public Read PlaceSource" ON "PlaceSource";
DROP POLICY IF EXISTS "Deny All Select PlaceSource" ON "PlaceSource";
DROP POLICY IF EXISTS "Deny All Insert PlaceSource" ON "PlaceSource";
DROP POLICY IF EXISTS "Deny All Update PlaceSource" ON "PlaceSource";
DROP POLICY IF EXISTS "Deny All Delete PlaceSource" ON "PlaceSource";
CREATE POLICY "Deny All Select PlaceSource" ON "PlaceSource" FOR SELECT TO PUBLIC USING (false);
CREATE POLICY "Deny All Insert PlaceSource" ON "PlaceSource" FOR INSERT TO PUBLIC WITH CHECK (false);
CREATE POLICY "Deny All Update PlaceSource" ON "PlaceSource" FOR UPDATE TO PUBLIC USING (false);
CREATE POLICY "Deny All Delete PlaceSource" ON "PlaceSource" FOR DELETE TO PUBLIC USING (false);

ALTER TABLE "VerificationLog" ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Public Read VerificationLog" ON "VerificationLog";
DROP POLICY IF EXISTS "Deny All Select VerificationLog" ON "VerificationLog";
DROP POLICY IF EXISTS "Deny All Insert VerificationLog" ON "VerificationLog";
DROP POLICY IF EXISTS "Deny All Update VerificationLog" ON "VerificationLog";
DROP POLICY IF EXISTS "Deny All Delete VerificationLog" ON "VerificationLog";
CREATE POLICY "Deny All Select VerificationLog" ON "VerificationLog" FOR SELECT TO PUBLIC USING (false);
CREATE POLICY "Deny All Insert VerificationLog" ON "VerificationLog" FOR INSERT TO PUBLIC WITH CHECK (false);
CREATE POLICY "Deny All Update VerificationLog" ON "VerificationLog" FOR UPDATE TO PUBLIC USING (false);
CREATE POLICY "Deny All Delete VerificationLog" ON "VerificationLog" FOR DELETE TO PUBLIC USING (false);

ALTER TABLE "DuplicateCandidate" ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Public Read DuplicateCandidate" ON "DuplicateCandidate";
DROP POLICY IF EXISTS "Deny All Select DuplicateCandidate" ON "DuplicateCandidate";
DROP POLICY IF EXISTS "Deny All Insert DuplicateCandidate" ON "DuplicateCandidate";
DROP POLICY IF EXISTS "Deny All Update DuplicateCandidate" ON "DuplicateCandidate";
DROP POLICY IF EXISTS "Deny All Delete DuplicateCandidate" ON "DuplicateCandidate";
CREATE POLICY "Deny All Select DuplicateCandidate" ON "DuplicateCandidate" FOR SELECT TO PUBLIC USING (false);
CREATE POLICY "Deny All Insert DuplicateCandidate" ON "DuplicateCandidate" FOR INSERT TO PUBLIC WITH CHECK (false);
CREATE POLICY "Deny All Update DuplicateCandidate" ON "DuplicateCandidate" FOR UPDATE TO PUBLIC USING (false);
CREATE POLICY "Deny All Delete DuplicateCandidate" ON "DuplicateCandidate" FOR DELETE TO PUBLIC USING (false);

ALTER TABLE "PlaceImage" ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Public Read PlaceImage" ON "PlaceImage";
DROP POLICY IF EXISTS "Deny All Select PlaceImage" ON "PlaceImage";
DROP POLICY IF EXISTS "Deny All Insert PlaceImage" ON "PlaceImage";
DROP POLICY IF EXISTS "Deny All Update PlaceImage" ON "PlaceImage";
DROP POLICY IF EXISTS "Deny All Delete PlaceImage" ON "PlaceImage";
CREATE POLICY "Public Read PlaceImage" ON "PlaceImage" FOR SELECT TO PUBLIC USING (true);
CREATE POLICY "Deny All Insert PlaceImage" ON "PlaceImage" FOR INSERT TO PUBLIC WITH CHECK (false);
CREATE POLICY "Deny All Update PlaceImage" ON "PlaceImage" FOR UPDATE TO PUBLIC USING (false);
CREATE POLICY "Deny All Delete PlaceImage" ON "PlaceImage" FOR DELETE TO PUBLIC USING (false);

ALTER TABLE "PlaceImageError" ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Public Read PlaceImageError" ON "PlaceImageError";
DROP POLICY IF EXISTS "Deny All Select PlaceImageError" ON "PlaceImageError";
DROP POLICY IF EXISTS "Deny All Insert PlaceImageError" ON "PlaceImageError";
DROP POLICY IF EXISTS "Deny All Update PlaceImageError" ON "PlaceImageError";
DROP POLICY IF EXISTS "Deny All Delete PlaceImageError" ON "PlaceImageError";
CREATE POLICY "Deny All Select PlaceImageError" ON "PlaceImageError" FOR SELECT TO PUBLIC USING (false);
CREATE POLICY "Deny All Insert PlaceImageError" ON "PlaceImageError" FOR INSERT TO PUBLIC WITH CHECK (false);
CREATE POLICY "Deny All Update PlaceImageError" ON "PlaceImageError" FOR UPDATE TO PUBLIC USING (false);
CREATE POLICY "Deny All Delete PlaceImageError" ON "PlaceImageError" FOR DELETE TO PUBLIC USING (false);

ALTER TABLE "ImageAudit" ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Public Read ImageAudit" ON "ImageAudit";
DROP POLICY IF EXISTS "Deny All Select ImageAudit" ON "ImageAudit";
DROP POLICY IF EXISTS "Deny All Insert ImageAudit" ON "ImageAudit";
DROP POLICY IF EXISTS "Deny All Update ImageAudit" ON "ImageAudit";
DROP POLICY IF EXISTS "Deny All Delete ImageAudit" ON "ImageAudit";
CREATE POLICY "Deny All Select ImageAudit" ON "ImageAudit" FOR SELECT TO PUBLIC USING (false);
CREATE POLICY "Deny All Insert ImageAudit" ON "ImageAudit" FOR INSERT TO PUBLIC WITH CHECK (false);
CREATE POLICY "Deny All Update ImageAudit" ON "ImageAudit" FOR UPDATE TO PUBLIC USING (false);
CREATE POLICY "Deny All Delete ImageAudit" ON "ImageAudit" FOR DELETE TO PUBLIC USING (false);

ALTER TABLE "Review" ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Public Read Review" ON "Review";
DROP POLICY IF EXISTS "Deny All Select Review" ON "Review";
DROP POLICY IF EXISTS "Deny All Insert Review" ON "Review";
DROP POLICY IF EXISTS "Deny All Update Review" ON "Review";
DROP POLICY IF EXISTS "Deny All Delete Review" ON "Review";
CREATE POLICY "Public Read Review" ON "Review" FOR SELECT TO PUBLIC USING (true);
CREATE POLICY "Deny All Insert Review" ON "Review" FOR INSERT TO PUBLIC WITH CHECK (false);
CREATE POLICY "Deny All Update Review" ON "Review" FOR UPDATE TO PUBLIC USING (false);
CREATE POLICY "Deny All Delete Review" ON "Review" FOR DELETE TO PUBLIC USING (false);

ALTER TABLE "Favorite" ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Public Read Favorite" ON "Favorite";
DROP POLICY IF EXISTS "Deny All Select Favorite" ON "Favorite";
DROP POLICY IF EXISTS "Deny All Insert Favorite" ON "Favorite";
DROP POLICY IF EXISTS "Deny All Update Favorite" ON "Favorite";
DROP POLICY IF EXISTS "Deny All Delete Favorite" ON "Favorite";
CREATE POLICY "Deny All Select Favorite" ON "Favorite" FOR SELECT TO PUBLIC USING (false);
CREATE POLICY "Deny All Insert Favorite" ON "Favorite" FOR INSERT TO PUBLIC WITH CHECK (false);
CREATE POLICY "Deny All Update Favorite" ON "Favorite" FOR UPDATE TO PUBLIC USING (false);
CREATE POLICY "Deny All Delete Favorite" ON "Favorite" FOR DELETE TO PUBLIC USING (false);

ALTER TABLE "HostListing" ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Public Read HostListing" ON "HostListing";
DROP POLICY IF EXISTS "Deny All Select HostListing" ON "HostListing";
DROP POLICY IF EXISTS "Deny All Insert HostListing" ON "HostListing";
DROP POLICY IF EXISTS "Deny All Update HostListing" ON "HostListing";
DROP POLICY IF EXISTS "Deny All Delete HostListing" ON "HostListing";
CREATE POLICY "Deny All Select HostListing" ON "HostListing" FOR SELECT TO PUBLIC USING (false);
CREATE POLICY "Deny All Insert HostListing" ON "HostListing" FOR INSERT TO PUBLIC WITH CHECK (false);
CREATE POLICY "Deny All Update HostListing" ON "HostListing" FOR UPDATE TO PUBLIC USING (false);
CREATE POLICY "Deny All Delete HostListing" ON "HostListing" FOR DELETE TO PUBLIC USING (false);

ALTER TABLE "HostListingImage" ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Public Read HostListingImage" ON "HostListingImage";
DROP POLICY IF EXISTS "Deny All Select HostListingImage" ON "HostListingImage";
DROP POLICY IF EXISTS "Deny All Insert HostListingImage" ON "HostListingImage";
DROP POLICY IF EXISTS "Deny All Update HostListingImage" ON "HostListingImage";
DROP POLICY IF EXISTS "Deny All Delete HostListingImage" ON "HostListingImage";
CREATE POLICY "Deny All Select HostListingImage" ON "HostListingImage" FOR SELECT TO PUBLIC USING (false);
CREATE POLICY "Deny All Insert HostListingImage" ON "HostListingImage" FOR INSERT TO PUBLIC WITH CHECK (false);
CREATE POLICY "Deny All Update HostListingImage" ON "HostListingImage" FOR UPDATE TO PUBLIC USING (false);
CREATE POLICY "Deny All Delete HostListingImage" ON "HostListingImage" FOR DELETE TO PUBLIC USING (false);

ALTER TABLE "IngestionListing" ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Public Read IngestionListing" ON "IngestionListing";
DROP POLICY IF EXISTS "Deny All Select IngestionListing" ON "IngestionListing";
DROP POLICY IF EXISTS "Deny All Insert IngestionListing" ON "IngestionListing";
DROP POLICY IF EXISTS "Deny All Update IngestionListing" ON "IngestionListing";
DROP POLICY IF EXISTS "Deny All Delete IngestionListing" ON "IngestionListing";
CREATE POLICY "Deny All Select IngestionListing" ON "IngestionListing" FOR SELECT TO PUBLIC USING (false);
CREATE POLICY "Deny All Insert IngestionListing" ON "IngestionListing" FOR INSERT TO PUBLIC WITH CHECK (false);
CREATE POLICY "Deny All Update IngestionListing" ON "IngestionListing" FOR UPDATE TO PUBLIC USING (false);
CREATE POLICY "Deny All Delete IngestionListing" ON "IngestionListing" FOR DELETE TO PUBLIC USING (false);

ALTER TABLE "OwnerClaim" ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Public Read OwnerClaim" ON "OwnerClaim";
DROP POLICY IF EXISTS "Deny All Select OwnerClaim" ON "OwnerClaim";
DROP POLICY IF EXISTS "Deny All Insert OwnerClaim" ON "OwnerClaim";
DROP POLICY IF EXISTS "Deny All Update OwnerClaim" ON "OwnerClaim";
DROP POLICY IF EXISTS "Deny All Delete OwnerClaim" ON "OwnerClaim";
CREATE POLICY "Deny All Select OwnerClaim" ON "OwnerClaim" FOR SELECT TO PUBLIC USING (false);
CREATE POLICY "Deny All Insert OwnerClaim" ON "OwnerClaim" FOR INSERT TO PUBLIC WITH CHECK (false);
CREATE POLICY "Deny All Update OwnerClaim" ON "OwnerClaim" FOR UPDATE TO PUBLIC USING (false);
CREATE POLICY "Deny All Delete OwnerClaim" ON "OwnerClaim" FOR DELETE TO PUBLIC USING (false);

ALTER TABLE "PlaceVisit" ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Public Read PlaceVisit" ON "PlaceVisit";
DROP POLICY IF EXISTS "Deny All Select PlaceVisit" ON "PlaceVisit";
DROP POLICY IF EXISTS "Deny All Insert PlaceVisit" ON "PlaceVisit";
DROP POLICY IF EXISTS "Deny All Update PlaceVisit" ON "PlaceVisit";
DROP POLICY IF EXISTS "Deny All Delete PlaceVisit" ON "PlaceVisit";
CREATE POLICY "Deny All Select PlaceVisit" ON "PlaceVisit" FOR SELECT TO PUBLIC USING (false);
CREATE POLICY "Deny All Insert PlaceVisit" ON "PlaceVisit" FOR INSERT TO PUBLIC WITH CHECK (false);
CREATE POLICY "Deny All Update PlaceVisit" ON "PlaceVisit" FOR UPDATE TO PUBLIC USING (false);
CREATE POLICY "Deny All Delete PlaceVisit" ON "PlaceVisit" FOR DELETE TO PUBLIC USING (false);

ALTER TABLE "FavoriteCollection" ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Public Read FavoriteCollection" ON "FavoriteCollection";
DROP POLICY IF EXISTS "Deny All Select FavoriteCollection" ON "FavoriteCollection";
DROP POLICY IF EXISTS "Deny All Insert FavoriteCollection" ON "FavoriteCollection";
DROP POLICY IF EXISTS "Deny All Update FavoriteCollection" ON "FavoriteCollection";
DROP POLICY IF EXISTS "Deny All Delete FavoriteCollection" ON "FavoriteCollection";
CREATE POLICY "Deny All Select FavoriteCollection" ON "FavoriteCollection" FOR SELECT TO PUBLIC USING (false);
CREATE POLICY "Deny All Insert FavoriteCollection" ON "FavoriteCollection" FOR INSERT TO PUBLIC WITH CHECK (false);
CREATE POLICY "Deny All Update FavoriteCollection" ON "FavoriteCollection" FOR UPDATE TO PUBLIC USING (false);
CREATE POLICY "Deny All Delete FavoriteCollection" ON "FavoriteCollection" FOR DELETE TO PUBLIC USING (false);

ALTER TABLE "FavoriteInCollection" ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Public Read FavoriteInCollection" ON "FavoriteInCollection";
DROP POLICY IF EXISTS "Deny All Select FavoriteInCollection" ON "FavoriteInCollection";
DROP POLICY IF EXISTS "Deny All Insert FavoriteInCollection" ON "FavoriteInCollection";
DROP POLICY IF EXISTS "Deny All Update FavoriteInCollection" ON "FavoriteInCollection";
DROP POLICY IF EXISTS "Deny All Delete FavoriteInCollection" ON "FavoriteInCollection";
CREATE POLICY "Deny All Select FavoriteInCollection" ON "FavoriteInCollection" FOR SELECT TO PUBLIC USING (false);
CREATE POLICY "Deny All Insert FavoriteInCollection" ON "FavoriteInCollection" FOR INSERT TO PUBLIC WITH CHECK (false);
CREATE POLICY "Deny All Update FavoriteInCollection" ON "FavoriteInCollection" FOR UPDATE TO PUBLIC USING (false);
CREATE POLICY "Deny All Delete FavoriteInCollection" ON "FavoriteInCollection" FOR DELETE TO PUBLIC USING (false);

ALTER TABLE "Itinerary" ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Public Read Itinerary" ON "Itinerary";
DROP POLICY IF EXISTS "Deny All Select Itinerary" ON "Itinerary";
DROP POLICY IF EXISTS "Deny All Insert Itinerary" ON "Itinerary";
DROP POLICY IF EXISTS "Deny All Update Itinerary" ON "Itinerary";
DROP POLICY IF EXISTS "Deny All Delete Itinerary" ON "Itinerary";
CREATE POLICY "Deny All Select Itinerary" ON "Itinerary" FOR SELECT TO PUBLIC USING (false);
CREATE POLICY "Deny All Insert Itinerary" ON "Itinerary" FOR INSERT TO PUBLIC WITH CHECK (false);
CREATE POLICY "Deny All Update Itinerary" ON "Itinerary" FOR UPDATE TO PUBLIC USING (false);
CREATE POLICY "Deny All Delete Itinerary" ON "Itinerary" FOR DELETE TO PUBLIC USING (false);

ALTER TABLE "ItineraryDay" ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Public Read ItineraryDay" ON "ItineraryDay";
DROP POLICY IF EXISTS "Deny All Select ItineraryDay" ON "ItineraryDay";
DROP POLICY IF EXISTS "Deny All Insert ItineraryDay" ON "ItineraryDay";
DROP POLICY IF EXISTS "Deny All Update ItineraryDay" ON "ItineraryDay";
DROP POLICY IF EXISTS "Deny All Delete ItineraryDay" ON "ItineraryDay";
CREATE POLICY "Deny All Select ItineraryDay" ON "ItineraryDay" FOR SELECT TO PUBLIC USING (false);
CREATE POLICY "Deny All Insert ItineraryDay" ON "ItineraryDay" FOR INSERT TO PUBLIC WITH CHECK (false);
CREATE POLICY "Deny All Update ItineraryDay" ON "ItineraryDay" FOR UPDATE TO PUBLIC USING (false);
CREATE POLICY "Deny All Delete ItineraryDay" ON "ItineraryDay" FOR DELETE TO PUBLIC USING (false);

ALTER TABLE "ItineraryActivity" ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Public Read ItineraryActivity" ON "ItineraryActivity";
DROP POLICY IF EXISTS "Deny All Select ItineraryActivity" ON "ItineraryActivity";
DROP POLICY IF EXISTS "Deny All Insert ItineraryActivity" ON "ItineraryActivity";
DROP POLICY IF EXISTS "Deny All Update ItineraryActivity" ON "ItineraryActivity";
DROP POLICY IF EXISTS "Deny All Delete ItineraryActivity" ON "ItineraryActivity";
CREATE POLICY "Deny All Select ItineraryActivity" ON "ItineraryActivity" FOR SELECT TO PUBLIC USING (false);
CREATE POLICY "Deny All Insert ItineraryActivity" ON "ItineraryActivity" FOR INSERT TO PUBLIC WITH CHECK (false);
CREATE POLICY "Deny All Update ItineraryActivity" ON "ItineraryActivity" FOR UPDATE TO PUBLIC USING (false);
CREATE POLICY "Deny All Delete ItineraryActivity" ON "ItineraryActivity" FOR DELETE TO PUBLIC USING (false);

ALTER TABLE "ItineraryShare" ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Public Read ItineraryShare" ON "ItineraryShare";
DROP POLICY IF EXISTS "Deny All Select ItineraryShare" ON "ItineraryShare";
DROP POLICY IF EXISTS "Deny All Insert ItineraryShare" ON "ItineraryShare";
DROP POLICY IF EXISTS "Deny All Update ItineraryShare" ON "ItineraryShare";
DROP POLICY IF EXISTS "Deny All Delete ItineraryShare" ON "ItineraryShare";
CREATE POLICY "Deny All Select ItineraryShare" ON "ItineraryShare" FOR SELECT TO PUBLIC USING (false);
CREATE POLICY "Deny All Insert ItineraryShare" ON "ItineraryShare" FOR INSERT TO PUBLIC WITH CHECK (false);
CREATE POLICY "Deny All Update ItineraryShare" ON "ItineraryShare" FOR UPDATE TO PUBLIC USING (false);
CREATE POLICY "Deny All Delete ItineraryShare" ON "ItineraryShare" FOR DELETE TO PUBLIC USING (false);

